# Generated by Django 5.1.4 on 2025-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default='images/2.jpeg', help_text='Введите фото автора', null=True, upload_to='images', verbose_name='Фото автора'),
        ),
    ]
